### ISSUE TITLE
support for node-modules :global scoping

### ISSUE THREAD

**Issue by Nickman87** [atom/language-sass#172]
I'm using css-modules in my project where I use SASS as a css source. Some css classes have to be kept globally and you can do this by scoping them inside `:global { ... }`.

This does however break the syntax highlighting in Atom:
![image](https://cloud.githubusercontent.com/assets/870416/18127910/7ceaf50e-6f83-11e6-8eb8-4fc027d2a1fd.png)

Is this something you want to support?

**Comment by 50Wliu** [comment]
As css-modules is not included in the CSS or Scss specs, it wouldn't be appropriate for language-sass to support this.  This is something that would best fit in a community package, eg `language-css-modules`.

**Comment by dsifford** [comment]
@50Wliu Agree this isn't an issue for atom, but for vscode this is a huge issue. The SCSS language is built-in and cannot be overwritten (to my knowledge) without compiling a custom insiders release.

So can we perhaps reopen this discussion? What would it hurt to add in support for this?

**Comment by 50Wliu** [comment]
@dsifford does VSCode not support community language packages?  Can you not install community packages that inject rules or override tokenization for specific filetypes?  I try to make Atom's language packages as compatible as possible with both VSCode and Linguist, but I'm still of the belief that css-modules has no place in language-sass as it isn't part of the spec.  What it would hurt is long-term maintenance as maintainers will have to additionally update the css-modules rules and ensure they don't regress rather than just focusing on Sass.

**Comment by dsifford** [comment]
@50Wliu I hear ya. 

I could be severely misguided, but I am under the assumption that VSCode does not allow people to override or extend the built-in languages. The only thing that is allowed is adding languages that do not exist in the built-ins. (Maybe @bpasero could clarify this?)

After thinking about this some more, I still think that the few additional scopes could be added as they do not conflict with any current scopes, but I think maybe a better place to put them is in `language-css` so that they can be included where appropriate across the various style grammars.

The issue hands down right now for me (and I assume other VSCode users) is the fact that the built-ins are locked. Not sure how else to go about this.

**Comment by dsifford** [comment]
Having said all that, I suppose if it comes down to it, all I'd really need to do to cure my compulsiveness when it comes to having raw, uncolorized tokens in my grammar would be to set `:global` and `:local` as  variables and the various functions/properties as mixins and interpolate it. Way less than ideal, but an acceptable worst-case scenario.

**Comment by 50Wliu** [comment]
With holidays approaching I won't be able to get to this until next year.

**Comment by lee-dohm** [comment]
@dsifford I agree with @50Wliu that it wouldn't be appropriate for us to add support for this, especially since the workaround is rather simple for Atom. I also don't think it is appropriate for us to add a workaround in our code in whatever package, however minor, for what appears to be solely a VSCode problem. If you have an issue with VSCode, the appropriate place for you to discuss it is on the https://github.com/Microsoft/vscode repo.

**Comment by dsifford** [comment]
@lee-dohm Fair enough. Thanks for the response.
