### ISSUE TITLE
Miscellaneous CSS Properties Not Tokenized

### ISSUE THREAD

**Issue by sunjay** [atom/language-sass#182]
I'm using a not-so-well supported CSS property listed under [MDN's CSS Miscellaneous](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Miscellaneous) section. I noticed it was highlighted red despite being valid, so I tried all the miscellaneous ones:

![screenshot from 2016-10-14 14-19-39](https://cloud.githubusercontent.com/assets/530939/19398370/4b267f0c-921a-11e6-85ce-f7d3244946fd.png)

None of these should be red because as far as I know they are all valid. Please consult the MDN page I linked for more information about the individual properties themselves.

**Comment by esdoppio** [comment]
Define "valid." :)

To me, a property appearing in an MDN page or even the Candidate Recommendation doesn't mean anything, if it is not supported by the major browsers. And I'm quite happy that my editor can make unsupported properties stand out for me like this.

**Comment by sunjay** [comment]
I think the purpose of syntax highlighting should be to make reading code easier and catch common *syntax* errors. None of those properties are misspelled and all of them are in the CSS spec. That's what makes them valid. 

As for whether I should use them or not, that's up to me. They shouldn't be highlighted red if they're valid CSS properties, regardless of browser support.

**Comment by esdoppio** [comment]
Adding properties to the grammar is easy. All the specs are available online, we could add all the properties appear in them to the grammar today. The reasons we don't want to do that are

* The specs, esp. the Working Drafts, are liable to change, we don't want to add things only to remove them later.
* The specs, as their names suggest, are at best, recommendations—they are not mandatory—some features that appear in them are never implemented by the major browsers.
* We don't use a feature in stylesheets because it appears in the specs, but because we can actually use it with the target browsers. By *not* adding features that are not supported by the major browsers, we can actually help developers more. Try to think of this kind of highlighting as a kind reminder: be careful with these suckers, maybe you need the prefixed version? :)

That's also why we should add features based on browser support rather than appearance in the specs.

**Comment by sunjay** [comment]
I get what you're saying, but the big red highlight is not a kind reminder. It's a big indication that you're doing something illegal in CSS. That's the troubling part of all of this. 

If I include `all: unset` in my CSS, regardless of what browsers support, I'm writing valid CSS. My *syntax* highlighter, whose job is only to check syntax, should not incorrectly mark that as invalid. 

Like you said, adding properties to the grammar is easy. Removing them is hopefully easy as well. If you're really determined to warn people about properties that aren't fully implemented everywhere yet, maybe there should be another style applied to things that are still going through the recommendation process?

Either way, I still believe the big red highlight is a bug because those properties are not invalid. That should be fixed no matter what other additions are deemed appropriate. 

Several major browsers do already implement and support at least the `all` property (which is the reason I found this bug in the first place), so by your reasoning, at least that property should definitely get added. 

The big red highlight is very distracting and misleading when I haven't actually written anything incorrectly.

**Comment by esdoppio** [comment]
Yes, we should definitely put it in the grammar.

**Comment by esdoppio** [comment]
Rule: Add a feature only if at least two of the major browsers have implemented it. What do you think? @50Wliu

**Comment by 50Wliu** [comment]
This is where it becomes suggestive.  I think properties can be added if:

1. They're standardized
2. Two or more major browsers support it in an unprefixed form
3. There's no reason to assume that they're not going to be standardized in the near future
4. There's no reason to assume that they're going to be deprecated/removed in the near future

**Comment by esdoppio** [comment]
Can you elaborate on <q>They're standardized</q>? When the spec the feature is in becomes a Recommendation?

How about (both have to be true)
* They are in the Working Draft or above
* Implemented by at least two of the major browsers

Again, it's never really about the standards but the browser support—if the browsers choose not to support the feature, it doesn't mean anything coz people are able to use a feature only if it's supported (hence the Modernizr), and the implementation status can actually influence the standard itself. This is a perfect example, from [CSS2.2](https://www.w3.org/TR/CSS22/about.html#css2.2-v-css2):

<blockquote>
While many of the issues will be addressed by the upcoming CSS3 specifications, the current state of affairs hinders the implementation and interoperability of CSS2. The CSS 2.2 specification attempts to address this situation by:

<ul>
<li>Maintaining compatibility with those portions of CSS2 that are widely accepted and implemented.
<li>Where implementations overwhelmingly differ from the CSS2 specification, modifying the specification to be in accordance with generally accepted practice.
<li>Removing CSS2 features which, by virtue of not having been implemented, have been rejected by the CSS community. CSS 2.2 aims to reflect what CSS features are reasonably widely implemented for HTML and XML languages in general (rather than only for a particular XML language, or only for HTML).
</ul>
</blockquote>

**Comment by Alhadis** [comment]
> The specs, esp. the Working Drafts, are liable to change, we don't want to add things only to remove them later.

I'm sorry, *what*? Since when is that an issue...?

If flexbox proved anything, it's that browser support for budding technologies does *not* guarantee there'll be a breaking revision in future. Conversely, SCSS still supports obsoleted aural properties like `azimuth` and `elevation`, which are not only unsupported, but were hardly ever implemented to begin with.

Let's be practical: it shouldn't be the responsibility of a syntax highlighter to provide a pocket caniuse.com. To be honest, I don't think SCSS shouldn't even **be** highlighting unrecognised properties as errors (I don't work with precompilers, and my knowledge of Sass is minimal, so make of that what you will).

**Comment by esdoppio** [comment]
Maybe I didn't make my point clear enough. All I wanted to say was: please don't just add a feature because it shows up in a Working Draft or an MDN page, do at least minimal research.

And that's mainly for the package maintainers, not the issue reporter.

And `CSS.supports()` is at your disposal, so it's not that hard for a maintainer to find out the implementation status of a feature. Actually, it only takes minutes:

```html
  <body>
    <p>Supported features:</p>
    <ul id="supported"></ul>
    <p>Unsupported features:</p>
    <ul id="unsupported"></ul>

    <script>
    const features = [
      '(all: unset)',
      '(all: revert)',
      '(clip-path: url("#clip"))',
      '(clip-path: fill-box)',
      '(clip-path: stroke-box)',
      '(clip-path: view-box)',
      '(initial-letter: normal)',
      '(initial-letter-align: auto)',
      '(mask-type: alpha)',
      '(mask-type: luminance)',
      '(text-rendering: optimizeSpeed)',
      '(text-rendering: optimizeLegibility)',
      '(text-rendering: geometricPrecision)'
    ];

    features.forEach(function(v) {
      let id = CSS.supports(v) ? 'supported' : 'unsupported';
      let feature = document.createElement('li');
      feature.textContent = v;

      document.getElementById(id).appendChild(feature);
    });
    </script>
  </body>
```

So in this case, maybe `initial-letter` and `intial-letter-align` could wait. And if you actually take a min to read the spec, you don't even have to test for the `ime-mode`.

I like properties that are (if they are in fact) not well supported highlighted like this myself, coz more than sometimes I'm not the one who wrote the stylesheet that I'm editing. But I agree with you that maybe it could just not highlight it coz the red sign makes some people uncomfortable.

**Comment by Alhadis** [comment]
> Actually, it only takes minutes:

Nah, for me, it takes less than a second. =)

<img src="https://cloud.githubusercontent.com/assets/2346707/19623761/b4de5030-9924-11e6-9a96-e264c6fe81e1.png" width="805" alt="" />

Anyway, [this](https://github.com/atom/language-css/pull/99) may be of interest to you, @esdoppio. I have included "working draft"-level features in the property-name support, at least the ones that're already seeing browser support.

**Comment by 50Wliu** [comment]
> To be honest, I don't think SCSS shouldn't even be highlighting unrecognised properties as errors

I tend to agree with this.  Syntax errors are (sometimes) easy to highlight with language packages but as we've seen whitelisting every "supported" property out there tends to be troublesome to maintain.  Use a linter for that.

**Comment by nene** [comment]
Alternatively this list of valid properties could be customizable. So one could just go to the settings screen and list the non-standard properties one would like to use.

Though I'd really give my vote for leaving this linting-like task out of syntax-highlighting altogether.

**Comment by Alhadis** [comment]
@50Wliu You can close this: I had to shoot error highlighting in the head to achieve grammar linkage. Consider this solved.

**Comment by 50Wliu** [comment]
I mean, we should still count them as valid tag names though...

**Comment by Alhadis** [comment]
Not quite sure I follow, although that might be the fault of my sleep-deprivation more than anything...

**Comment by 50Wliu** [comment]
Ok I just tested this out and other than initial-letter and initial-letter-align all the names are recognized now.  I think it's safe to close because those two have no browser support as of yet.
