### ISSUE TITLE
Color for 'cursor' for sass (SCSS) is wrong

### ISSUE THREAD

**Issue by aeschli** [atom/language-sass#226]
_From @Binaryify on July 18, 2017 7:24_

- VSCode Version:1.14.1
- OS Version: 10.12.5
'cursor' had wrong color in SCSS file, but in the css file it had right color
![image](https://user-images.githubusercontent.com/12221718/28305141-1a491574-6bcd-11e7-8e66-bf9c342983ec.png)
![image](https://user-images.githubusercontent.com/12221718/28305153-21d9d08a-6bcd-11e7-8292-d0aca564563c.png)
 The 'cursor' key had the same scope with html tag in the 'scss' file
![image](https://user-images.githubusercontent.com/12221718/28305185-41968a3a-6bcd-11e7-8aea-5669b3e43649.png)
![image](https://user-images.githubusercontent.com/12221718/28305188-46ca8718-6bcd-11e7-8601-1de8e1605246.png)

_Copied from original issue: Microsoft/vscode#30907_

**Comment by usernamehw** [comment]
Also applies to `mask`, `content`, `filter`, `font`
```scss
body {
    cursor: pointer;
    ::before {
        content: '';
    }
    filter: blur(5px);
    font: 12px/14px sans-serif;
    mask: none;
}
```

**Comment by thismarcoantonio** [comment]
There is any update to this? I still getting the wrong highlight for `cursor`, `content` and `mask` properties

**Comment by gerasimvol** [comment]
`caret-color` same bug

**Comment by pgrantmartello** [comment]
The relevant line of code causing this is here: https://github.com/atom/language-css/blob/master/grammars/css.cson#L2073

**Comment by jdsteinbach** [comment]
It appears that `content`, `cursor`, `filter`, `font`, `mask` are mis-highlighted in `scss`; possibly related to the [`property-names`](https://github.com/atom/language-css/blob/master/grammars/css.cson#L1488) vs [`tag-names`](https://github.com/atom/language-css/blob/master/grammars/css.cson#L2056) overlap

**Comment by cssinate** [comment]
@gerasimvol - it appears the same, but it isn't. caret-color should be listed in here, but it isn't. https://github.com/atom/language-css/blob/master/grammars/css.cson#L2056

I would guess it's probably because that property is still a recommendation, and not a final draft, but they might accept a PR adding it in. You should try adding it!

**Comment by pgrantmartello** [comment]
It looks like @dsifford fixed this two years ago. Either it was not fixed properly, or the bug has come up again.

https://github.com/atom/language-sass/pull/234

**Comment by cssinate** [comment]
It looks like @dsifford tried to fix this two years ago. Either it didn't fix it, or the problem has come back again for some reason.

https://github.com/atom/language-sass/pull/234

**Comment by Aerijo** [comment]
@cssinate The PR history shows that it caused another error (#237), and so was reverted in #238

**Comment by cssinate** [comment]
@Aerijo - good catch. Sorry I missed it. I don't think I have the skills to go and fix the problem. But it seems like the logic should be:

"If the string is followed by a `:` and that `:` is not followed by one of the pseudo-elements or pseudo-selectors, then it's a property."

**Comment by cssinate** [comment]
I attempted a pull request with a fix for this issue, but the tests are failing. I don't know enough about the tests to understand what they're complaining about. It seems like it breaks because it doesn't like the name or the scope that `font` has. However, font is both a valid property name and a valid (though deprecated) HTML tag. If someone has some insight about where we can go from here, I'm all for it!

**Comment by gerasimvol** [comment]
@cssinate https://github.com/cssinate/scss-language-improvements/issues/2

**Comment by ronilaukkarinen** [comment]
Just bumping to say I noticed these too. As I do SCSS daily it would be nice to have these implemented instead of a separate plugin. As not experienced enough, using [cssinate.scss-language-improvements](https://marketplace.visualstudio.com/items?itemName=cssinate.scss-language-improvements) for now, as others.

**Comment by artuska** [comment]
Any progress?

**Comment by cssinate** [comment]
@artuska - yes. Read the last two references from before you posted.

**Comment by cssinate** [comment]
So here's a quick update. The problem for VSCode [should be solved by the end of this month](https://github.com/microsoft/vscode/issues/115480). The thing is, there's been a fix for this in Atom for 3 years:

https://github.com/atom/language-css/blob/57531cce71821d4bd4493a2a90c12170344a56dd/grammars/css.cson#L2092

For those that aren't super familiar with Regex, there's a bit in there that says, "a tag name can be followed with a `:` so long as that `:` isn't followed by a space."

When I edit the grammar file in VSCode directly and locally on my machine, it's fixed. This makes me confident that it will be fixed in VSCode. However, Atom is strange. If you create a SCSS file in Atom, and just write:

```scss
div {
  cursor: url('');
}
```

Cursor is highlighted incorrectly in Atom still! **HOWEVER**, if I fork atom/language-css and I change nothing, and I run Atom in dev mode using that package, it works properly!

![image](https://user-images.githubusercontent.com/25226452/107678213-1e42eb00-6c69-11eb-8dc7-a103fb35a8a8.png)

Atom dev mode on the left, and just the regular Atom that I downloaded today on the right. I can't explain why this is happening, and I'm not going to try to fix this. I don't use Atom. But Atom users that still care about this issue, I hope this gets you close enough to figure out what's going on.

**Comment by ronilaukkarinen** [comment]
Quoting myself after some years.

> Just bumping to say I noticed these too. As I do SCSS daily it would be nice to have these implemented instead of a separate plugin. As not experienced enough, using [cssinate.scss-language-improvements](https://marketplace.visualstudio.com/items?itemName=cssinate.scss-language-improvements) for now, as others.

[SCSS language improvements](https://marketplace.visualstudio.com/items?itemName=cssinate.scss-language-improvements) extension is no longer available and this is present again...

![Screen-Shot-2022-05-18-15-21-01 97](https://user-images.githubusercontent.com/1534150/169037449-8aad14dd-d1a6-4dee-a28f-a491af43a57d.png)

```
Version: 1.68.0-insider (Universal)
Commit: 688c80245936b49b7ceca494d9edfe97cae06f8a
Date: 2022-05-18T05:15:18.598Z (7 hrs ago)
Electron: 17.4.3
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.3.0
```

**Comment by cssinate** [comment]
@ronilaukkarinen - Here's what I've found.

https://github.com/atom/language-css/commit/21cfdb766587c351ac9873ecce0075b8c05799c5

The commit above fixed the issue for syntax highlighting. However, according to this:

https://github.com/atom/language-css/pull/127#issuecomment-883432402

This change broke auto-completions, so the change was reverted.

So either the regex for property names needs to be written to take pseudo-selectors auto-completion into account or auto-completion needs to be modified to be smarter about what should or shouldn't be auto-completed and how.

**Comment by ronilaukkarinen** [comment]
Thank you a lot @cssinate for taking a look! This issue definitely needs to be reopened.

**Comment by ronilaukkarinen** [comment]
Just FYI, I've improved the original extension by @cssinate and re-published [my fork](https://github.com/ronilaukkarinen/scss-language-improvements) to [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ronilaukkarinen.scss-language-improvements) so whoever is also bugged by this issue can use it while waiting for the official fix.
