### ISSUE TITLE
Vue broken ::v-deep highlighting

### ISSUE THREAD

**Issue by thinkerdu** [atom/language-sass#274]
![image](https://user-images.githubusercontent.com/28700378/69513029-69e47880-0f81-11ea-9c6b-0d7d737028d8.png)
![image](https://user-images.githubusercontent.com/28700378/69513031-6ea92c80-0f81-11ea-9820-d67a0c3f61b4.png)

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by thinkerdu** [comment]
Might relate to [this issue](https://github.com/atom/language-sass/issues/254)
