### ISSUE TITLE
From and to keywords highlight inside @keyframes definition

### ISSUE THREAD

**Issue by gfpacheco** [atom/language-sass#44]
`from` and `to` keywords aren't being colored properly:
![screenshot from 2015-01-08 10 57 43](https://cloud.githubusercontent.com/assets/3705660/5662812/5d65a39c-9725-11e4-86d0-a845559caa7e.png)

I think the right way to do it is matching them only when inside `@keyframes` definitions, but I don't know how to do it.

**Comment by silvenon** [comment]
The problem is that after `@keyframes anim` the grammar matches `{` and `}` as a property list. It needs to match them as special `@keyframes` selector list which will only match `(from|to|\d+%)` as "selectors". Or something like that.

I'm currently diving into grammars, when I get the hang of it I'll try to fix this.
