### ISSUE TITLE
`order` property (flex-box) is highlighted in red

### ISSUE THREAD

**Issue by haggen** [atom/language-sass#45]
![SASS incorrect highlight](https://cloud.githubusercontent.com/assets/270076/5683531/c624f0e6-980f-11e4-9490-0ee9582b6105.png)

Info on `order`: https://developer.mozilla.org/en-US/docs/Web/CSS/order

**Comment by jplatte** [comment]
+1

When looking at the language-css grammar file, I found that it doesn't know this property (as well as other flexbox stuff) either. It isn't highlighted as error though, simply highlighted in another color (slightly darker grey in the atom-dark theme). Maybe it would be a good idea to the same here, instead of highlighting all unknown keywords as errors.

**Comment by jplatte** [comment]
Thanks! :)
