### ISSUE TITLE
Support for single line comments

### ISSUE THREAD

**Issue by itsjustmath** [atom/language-sass#66]
![atom_sass_example_comment](https://cloud.githubusercontent.com/assets/635044/7996979/630b3382-0adb-11e5-90d1-5a26ba24eda4.png)

When clicking `CMD` + `/` the editor creates a multiline comment by default.

It would be great if there was an option to choose between [multiline comments and single line comments](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#comments).

> The multiline comments are preserved in the CSS output where possible, while the single-line comments are removed

I believe Sublime Text does the single-line comment behavior by default if you need an idea of intended usage.

**Comment by mnquintana** [comment]
I can't reproduce this with Atom 0.206.0-8abdc67 and language-sass 0.38.0 – can you reproduce this in safe mode? There have been [a few](https://github.com/atom/language-sass/issues/32) of [these reports](https://github.com/atom/language-less/issues/31) before, and they've all been caused by a community package (emmet, in this case).

**Comment by itsjustmath** [comment]
My apologies! Disabling emmet fixed the issue. I'll file a bug with them. Thanks!
